server:
 port: 8088
######注意格式，需要顶格写
spring:
   datasource: # 数据源的相关配置
     url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
     password: root
   redis:
  #单机单实例
    database: 1
    host: localhost  #本地
    #host: 192.168.50.131
    port: 6379
    #password: redis
  #Redis 哨兵模式
     #database: 1
     #password: redis
     #sentinel:
         #昵称--在redis配置文件中设置的
      #master: mymaster
         #集群节点，IP+端口号，redis由哨兵接管
       #nodes: 192.168.50.129:26379,192.168.50.131:26379,192.168.50.132:26379
  #Redis 集群模式
    # password: redis
     # database: 1  默认16个，不写为0，在集群下是一个整体可以不用写
    # cluster:
    #   nodes: 192.168.50.129:6379,192.168.50.131:6379,192.168.50.132:6379...六台节点

mybatis:
   configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


