server:
 port: 8088
######注意格式，需要顶格写
spring:
   datasource: # 数据源的相关配置
     url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
     password: root
   redis:
    database: 1
    #host: localhost  本地
    host: 192.168.50.131
    port: 6379
    password: redis

mybatis:
   configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


